### ISSUE TITLE
Extension not showing list of sound cards

### ISSUE THREAD

**Issue by vboufleur** [kgshank/gse-sound-output-device-chooser#5] opened 2015-12-24 20:54 UTC
This extension is not appearing below my volume slider. My gnome-shell version is '3.16.4'. My OS is 'Ubuntu Gnome 15.10'.

This is my volume slider:
![captura de tela de 2015-12-24 18-46-06](https://cloud.githubusercontent.com/assets/16310611/11997828/6595df1a-aa6f-11e5-958e-492cc8319bae.png)

Just ask if you want any extra information.

**Comment by kgshank** [comment] 2015-12-25 02:06
Restart shell with only this extension is enabled from terminal and check whether any errors are printed. Make sure pulse audio is working properly and you see devices in gnome control center sound settings.

**Comment by vboufleur** [comment] 2015-12-26 00:31
After disabling all extensions except this one it started to work. Then I enabled all extensions back again and rebooted and it kept working. Thanks for the help, I'm going to leave this comment if anyone stumbles upon this.

**Comment by vboufleur** [comment] 2015-12-26 17:14
Hi, this issue happened again. This is the error printed on the console:

(gnome-shell:11855): Gjs-WARNING **: JS ERROR: TypeError: stream.get_port(...) is null
SoundOutputDeviceChooser<._lateInit@(MY HOME FOLDER)/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:48

**Comment by vboufleur** [comment] 2015-12-26 18:00
Maybe a simple null check will solve this issue

**Comment by kgshank** [comment] 2016-01-05 13:17
Thanks for the info. I will modify the code accordingly. I am working on
some additional features in the extension, so please bear with me until the
change gets implemented

**Comment by vboufleur** [comment] 2016-01-07 05:19
Thanks! Comment here when you push the new version and I'll test this issue.

**Comment by felixsanz** [comment] 2016-01-07 23:32
Ill test it too because here is broken and i can't activate the extension. Thanks!

**Comment by kgshank** [comment] 2016-01-24 16:59
There is a new update in gnome extension site. Please verify whether the issue is fixed

**Comment by felixsanz** [comment] 2016-01-25 06:59
Still the same problem. I installed the extension manually, not using gnome extension site. And i get this:

![Error](http://i.imgur.com/UacO9tQ.png)

But i still don't know how i can debug it. if you give me a hand i'll paste here the errors

**Comment by kgshank** [comment] 2016-01-25 07:20
@felixsanz Try looking glass, (Alt + F2 -> lg) under the extensions tab you should see the extension listed. Click on the "show errors" option and send me the content

**Comment by felixsanz** [comment] 2016-01-25 08:15
it says "sound-output-device-chooser@kgshank has not emmited any error"

**Comment by kgshank** [comment] 2016-01-25 09:52
Disable all extensions except this extension and run this command `gnome-shell -r&` in terminal. You should some messages from the extension. Send them to me

**Comment by felixsanz** [comment] 2016-01-25 19:20
Here it goes:

> (gnome-shell:15334): Gjs-WARNING **: JS ERROR: Exception in callback for signal: extension-found:  Error: No JS module 'convenience' found in search path @/usr/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/extension.js:25

**Comment by kgshank** [comment] 2016-01-26 06:35
Your installation seems to be missing a file. Remove the extension completely from /usr/share/gnome-shell/extensions, reinstall from https://extensions.gnome.org/extension/906/sound-output-device-chooser/ and then move the folder to /usr/share/gnome-shell/extensions

**Comment by felixsanz** [comment] 2016-01-26 10:11
Fixed. The AUR package for Arch is broken, but installing this using extensions.gnome.org works. Thanks!

**Comment by kgshank** [comment] 2016-01-26 16:08
Thanks, closing the issue

**Closed by kgshank** 2016-01-26 16:08 UTC
