### ISSUE TITLE
Locking gnome screen/session duplicates entries in both input/output sections

### ISSUE THREAD

**Issue by Kallestofeles** [kgshank/gse-sound-output-device-chooser#87] opened 2020-02-18 17:27 UTC
Greetings,

Locking the screen/session duplicated the entries in both the input and the output sections of the plugin. Here is an example after locking the screen twice:
![image](https://user-images.githubusercontent.com/3207177/74761370-96f4ae80-5284-11ea-91f8-fdd0618014da.png)

Reproduce:
1) Lock the screen/session
2) Wait 5 seconds
3) Unlock your screen/session

**Comment by kgshank** [comment] 2020-03-04 15:17
Duplicate of #41

**Closed by kgshank** 2020-03-04 15:17 UTC
