### ISSUE TITLE
When a new device is plugged, the selector of the extension automatically select it but in fact it is not. The user needs to select another device and then go back to the newly plugged device selection.

### ISSUE THREAD

**Issue by Fade78** [kgshank/gse-sound-output-device-chooser#147] opened 2021-03-24 08:07 UTC
First, thank you for this awesome extension. Very useful for many people!

This bug appeared a long time ago and persist through several linux install. Now in Ubuntu 20.10.

**Describe the bug**
If I plug a new sound device, it appears in the extension and is automatically selected. But the source of the sound is actually not changed. So there is a mismatch between what is displayed (the new source device) and what I hear (the previously selected sound device). In order to hear the new sound device, I have to select another sound device (most of the time, the old one) and then go back to to the new sound device. Then it works.

**Extension Information**
* Shell Version: 3.38.3
* Extension Version: 35 (gnome-extensions info sound-output-device-chooser@kgshank.net)
* Install method: extension.gnome.org
* OS: Ubuntu 20.10

**Error / Journal messages**
See below: [example 1](https://github.com/kgshank/gse-sound-output-device-chooser/issues/147#issuecomment-809201851) and [example 2](https://github.com/kgshank/gse-sound-output-device-chooser/issues/147#issuecomment-809264421).

**Comment by kgshank** [comment] 2021-03-24 19:08
Enable Log messages in extension preferences and share the output of `journalctl -r | grep  SDC`

**Comment by andrebrait** [comment] 2021-03-29 08:35
Yup, experiencing the same here when I connect my Bluetooth headphones. It doesn't happen for input devices, only for output.

**Comment by Fade78** [comment] 2021-03-29 08:47
> Enable Log messages in extension preferences and share the output of `journalctl -r | grep SDC`

I enabled the logs. I'll be back to you as soon as the bug occurs again.

**Comment by Wouter0100** [comment] 2021-03-29 08:55
> Yup, experiencing the same here when I connect my Bluetooth headphones. It doesn't happen for input devices, only for output.

Having the same issue here.

**Comment by Fade78** [comment] 2021-03-29 08:57
- Playing Spotify on the line output, to the speaker.
- Unplugging the USB sound card of the Gamecom headphone
- Plungin it again
- The headphone are now selected in the extension interface
- But the music still plays through the speakers (line out)
- I have to select back the line out and then again the headphone to listen through the headphone

```
mars 29 10:49:23 Carri01 gnome-shell[3444]: SDC Debug: Removed: 27:Microphone - GameCom 777 5.1 Headset
mars 29 10:49:23 Carri01 gnome-shell[3444]: SDC Debug: Removed: 25:Analog Output - GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Added - 28
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: New logic
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Python found.python
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards iec958-stereo-output for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards iec958-stereo-output for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Device Name:Digital Output (S/PDIF) - GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Added: 28:Digital Output (S/PDIF):iec958-stereo-output:GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Removed: 28:Digital Output (S/PDIF) - GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Added - 29
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: New logic
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Python found.python
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-output for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-output for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-output for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Device Name:Analog Output - GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Added: 29:Analog Output:analog-output:GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Added - 30
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: New logic
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Python found.python
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards multichannel-input for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards multichannel-input for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards multichannel-input for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Device Name:Multichannel Input - GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Added: 30:Multichannel Input:multichannel-input:GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Removed: 30:Multichannel Input - GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Added - 31
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: New logic
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Python found.python
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-input-mic for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-input-mic for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-input-mic for card id undefined
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Device Name:Microphone - GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Added: 31:Microphone:analog-input-mic:GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Activated:- 29
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Activated: 29:Analog Output - GameCom 777 5.1 Headset
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Activated:- 31
mars 29 10:49:28 Carri01 gnome-shell[3444]: SDC Debug: Activated: 31:Microphone - GameCom 777 5.1 Headset
```
![debugsound](https://user-images.githubusercontent.com/1572834/112812474-7a2ccc00-907d-11eb-8a14-8c3547e64c51.png)

**Comment by Fade78** [comment] 2021-03-29 10:22
Same thing here:
Listening through Gamecom headset, connecting wireless Stealh 600 headset: while the display switch to the 600, the sound is still in the Gamecom.

```
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Added - 32
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: New logic
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Python found.python
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards iec958-stereo-output for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards iec958-stereo-output for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Device Name:Digital Output (S/PDIF) - Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Added: 32:Digital Output (S/PDIF):iec958-stereo-output:Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Removed: 32:Digital Output (S/PDIF) - Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Added - 33
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: New logic
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Python found.python
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-output for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-output for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-output for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Device Name:Analog Output - Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Added: 33:Analog Output:analog-output:Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Added - 34
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: New logic
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Python found.python
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards multichannel-input for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards multichannel-input for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards multichannel-input for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Device Name:Multichannel Input - Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Added: 34:Multichannel Input:multichannel-input:Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Removed: 34:Multichannel Input - Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Added - 35
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: New logic
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Python found.python
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-input-mic for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-input-mic for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Getting profile from cards analog-input-mic for card id undefined
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Device Name:Microphone - Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Added: 35:Microphone:analog-input-mic:Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Activated:- 33
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Activated: 33:Analog Output - Stealth 600
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Activated:- 35
mars 29 12:20:58 Carri01 gnome-shell[3444]: SDC Debug: Activated: 35:Microphone - Stealth 600
```

**Comment by kgshank** [comment] 2021-03-29 11:17
i dont have spotify to test. With lollipop, I cant reproduce this behaviour , the audio switches back to my headset or speakers. It might be related to the sound settings in spotify. 

After plugging in  the headset, dont change the device in the extension, check whether the default device is changed in gnome settings. 

If the device does not match then its a problem with the extension. If both match, then the problem is not with the extension, as this extension is meant to be a shortcut for the sound settings.

**Comment by Wouter0100** [comment] 2021-03-30 07:35
@kgshank in that case it seems to be a bug in Gnome. The output device is also set to the Headphones in the settings, but it does not actually output any audio - this is still through the old output device. A switch back and forth is required to get it to actually work.

**Comment by kgshank** [comment] 2021-03-30 09:23
Yes, it seems to be a problem with gnome / pulseaudio. Please report the behaviour with gnome, with the extension disabled.

**Comment by terencode** [comment] 2021-03-31 13:34
I don't know if I should open a new issue or if it's the same bug but  when resuming from suspend my usb soundcard disconnects. This is not related to the extension but the problem is when I plug it back in, the extension doesn't list it in the menu and I need to do a shell restart for it to appear.

**Comment by kgshank** [comment] 2021-04-01 19:15
@terencode can you post the messages after the system resumes and the soundcard is not listed. This error is fixed in the current versions

**Comment by terencode** [comment] 2021-04-08 13:58
Sorry I didn't see there was a new toggle to activate the new detection system. I will try it and tell you if I still has the issue.

**Closed** 2021-04-09 19:42 UTC
